<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
   
    $config['full_tag_open'] = '<ul class="pagination pagination-sm" style="margin-top: -10px;">';
    $config['full_tag_close'] = '</ul>';
    $config['num_tag_open'] = '<li>';
    $config['num_tag_close'] = '</li>';
    $config['cur_tag_open'] = '<li class="active"><span>';
    $config['cur_tag_close'] = '<span class="sr-only">(current)</span></span></li>';
    $config['prev_tag_open'] = '<li>';
    $config['prev_tag_close'] = '</li>';
    $config['next_tag_open'] = '<li>';
    $config['next_tag_close'] = '</li>';
    $config['first_link'] = 'First';
    $config['prev_link'] = 'Previous';
    $config['last_link'] = 'Last';
    $config['next_link'] = 'Next';
    $config['first_tag_open'] = '<li>';
    $config['first_tag_close'] = '</li>';
    $config['last_tag_open'] = '<li>';
    $config['last_tag_close'] = '</li>';